### ISSUE TITLE
nginx config & prefix paths on Windows

### ISSUE THREAD

**Issue by crusaderltd** [alexcurtis/grunt-nginx#4]
I have nginx installed to `c:\nginx\`, and a node app at `c:\node\stock\`. I have my `gruntfile.js` at `c:\node\stock\gruntfile.js`.

I tried `config: 'c:\\nginx\\conf\\nginx.conf'` and `prefix: 'c:\\nginx'`. Also `config: '../../nginx/conf/nginx.conf'` and `prefix: '../../nginx/'`.

I'm getting this error message:

> Exception thrown in attempt to start nginx: Error: Error: not found: nginx

What should these paths be..?

**Comment by alexcurtis** [comment]
'nginx' needs to be in your PATH. On windows this is done via environment variables.

**Comment by crusaderltd** [comment]
Thanks Alex!

It's working now, after adding to the PATH env vars and a console restart.

Very helpful node package... 

Cheers!
